<?php require_once 'includes/common.php'; require_login(); $stats = fetch_dashboard_stats($conn); ?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Export Center</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/app.css"></head><body>
<div class="app-shell app-shell-form"><section class="card form-page-card"><div class="form-page-top"><div><div class="eyebrow">Reporting & Downloads</div><h1 class="hero-page-title">Export Center</h1><p class="hero-page-subtitle">Generate CSV or print-ready PDF views for inventory operations without leaving the system.</p></div><a class="btn btn-soft" href="dashboard.php">Back to Dashboard</a></div>
<div class="export-grid">
    <div class="export-card"><h2 class="section-title">Regular Inventory</h2><p class="section-subtitle">Export the regular inventory table with available, in, out, and returned quantities.</p><div class="inline-actions"><a class="btn btn-primary" href="export_inventory.php?scope=regular&format=csv">Export Excel / CSV</a><a class="btn btn-outline" target="_blank" href="export_inventory.php?scope=regular&format=pdf">Open PDF View</a></div></div>
    <div class="export-card"><h2 class="section-title">Outsourced Inventory</h2><p class="section-subtitle">Export outsourced batches including distributor visibility.</p><div class="inline-actions"><a class="btn btn-primary" href="export_inventory.php?scope=outsourced&format=csv">Export Excel / CSV</a><a class="btn btn-outline" target="_blank" href="export_inventory.php?scope=outsourced&format=pdf">Open PDF View</a></div></div>
    <div class="export-card"><h2 class="section-title">Full Inventory</h2><p class="section-subtitle">Export combined regular and outsourced stock in one report.</p><div class="inline-actions"><a class="btn btn-primary" href="export_inventory.php?scope=all&format=csv">Export Excel / CSV</a><a class="btn btn-outline" target="_blank" href="export_inventory.php?scope=all&format=pdf">Open PDF View</a></div></div>
    <div class="export-card"><h2 class="section-title">Operational Reports</h2><p class="section-subtitle">Use the live app views for alerts, activity, and batch history before printing.</p><div class="inline-actions"><a class="btn btn-soft" href="alerts.php">Open Alerts Center</a><a class="btn btn-soft" href="activity_logs.php">Open Activity Log</a><a class="btn btn-soft" href="batch_history.php">Open Batch History</a></div></div>
</div>
<div class="card info-banner" style="margin-top:18px;"><strong>Quick snapshot:</strong> <?php echo number_format((int)$stats['regular_items'] + (int)$stats['outsourced_items']); ?> total batches • <?php echo number_format((int)$stats['low_stock']); ?> low stock • <?php echo number_format((int)$stats['expiring_soon']); ?> expiring soon</div>
</section></div></body></html>
